name: poetry-server

on:
  push:
    branches: [main]

jobs: 
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: deploy files to server
        uses: garygrossgarten/github-action-scp@release
        with:  
          local: ../poetry-server
          remote: '/home/ps'
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.PASSWORD}}